// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrdTfHl0DqbxiV3xVHRiCpyuEbFJz1P3A',
    appId: '1:989578421125:web:9329304f828d57920d9aec',
    messagingSenderId: '989578421125',
    projectId: 'smart-expense-manager-72856',
    authDomain: 'smart-expense-manager-72856.firebaseapp.com',
    storageBucket: 'smart-expense-manager-72856.firebasestorage.app',
    measurementId: 'G-0XMG110LEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4U3lYUlxGfYcQKuyJHQSVI8xV52Ghe6k',
    appId: '1:989578421125:android:c7556f1a3bd0bdef0d9aec',
    messagingSenderId: '989578421125',
    projectId: 'smart-expense-manager-72856',
    storageBucket: 'smart-expense-manager-72856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPxf3T0SRvdURAVHPGuGDZb-KkJcysNw4',
    appId: '1:989578421125:ios:7d78a3caa1725f520d9aec',
    messagingSenderId: '989578421125',
    projectId: 'smart-expense-manager-72856',
    storageBucket: 'smart-expense-manager-72856.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPxf3T0SRvdURAVHPGuGDZb-KkJcysNw4',
    appId: '1:989578421125:ios:7d78a3caa1725f520d9aec',
    messagingSenderId: '989578421125',
    projectId: 'smart-expense-manager-72856',
    storageBucket: 'smart-expense-manager-72856.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrdTfHl0DqbxiV3xVHRiCpyuEbFJz1P3A',
    appId: '1:989578421125:web:6415960bc359959c0d9aec',
    messagingSenderId: '989578421125',
    projectId: 'smart-expense-manager-72856',
    authDomain: 'smart-expense-manager-72856.firebaseapp.com',
    storageBucket: 'smart-expense-manager-72856.firebasestorage.app',
    measurementId: 'G-LVDLXXHHMC',
  );
}
